/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.carrotsearch.gradle.opts;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.Test;

import static org.junit.Assert.assertNotNull;

/** A simple unit test. */
public class OptsPluginTest {
  @Test
  public void pluginRegistersATask() {
    // Create a test project and apply the plugin
    Project project = ProjectBuilder.builder().build();
    project.getPlugins().apply("com.carrotsearch.gradle.opts");

    // Verify the result
    assertNotNull(project.getTasks().findByName("greeting"));
  }
}
