/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.carrotsearch.gradle.opts;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.Assert;
import org.junit.Test;

/** A simple unit test. */
public class OptsPluginTest {
  @Test
  public void registersUtilityMethods() {
    Project project = ProjectBuilder.builder().build();
    project.getPlugins().apply("com.carrotsearch.gradle.opts");

    // Verify the result
    OptsPluginExtension opts = (OptsPluginExtension) project.getExtensions().findByName("opts");
    Assert.assertNotNull(opts);

    Object defValue = "default-value";
    Assert.assertEquals(defValue, opts.optOrDefault("non-existent", defValue));
    Assert.assertEquals(defValue, opts.envOrDefault("non-existent", defValue));
    Assert.assertEquals(defValue, opts.optOrEnvOrDefault("non-existent", "non-existent", defValue));
  }
}
